server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /springBoot


## SpringBoot配置文件，使用yml格式的配置文件

## 配置数据源
spring:
  # freemarker视图模型
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    check-template-location: true
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  datasource:
   # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql新版连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    # 说明： 新版驱动url默认地址为127.0.0.1:3306，所以访问本机mysql数据库地址可以用 /// 表示
    url: jdbc:mysql:///springboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: admin
    # druid配置
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙log4j2， 'stat'表示使用监控过滤器
      filters: stat,wall,log4j2
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

## mybatis配置
mybatis:
  mapper-locations: classpath*:com/qiuzq/**/mapper/*.xml #扫描配置;对应mapper映射xml文件的所在路径
  type-aliases-package: com.qiuzq.model # 别名配置;对应的model路径



## pageHelper分页插件
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true

## 日志配置
logging:
  config: classpath:log4j2.xml
  level:
    com.qiuzq.mapper: DEBUG